import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NavBar from "@/components/NavBar/NavBar";
import { BG } from "@/components/styledComponents/BG.styled";
import StyledJsxRegistry from "./registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MyBooks.leo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <link rel="icon" href="images/favicon.png" />
      <body className={inter.className}>
        <StyledJsxRegistry>
          <BG />
          <NavBar />
          <main>
            {children}
          </main>
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
